### ISSUE TITLE
Found simple a svg that takes quite some time to render

### ISSUE THREAD

**Issue by equinox2k** [ElinamLLC/SharpVectors#107]
Found simple a svg that takes quite some time to render, however I know its corrupt in some kind of way. Rendering in browser however is instant.

Link to svg in question...

[https://gist.github.com/equinox2k/4e72b3fcdd9ae3e4d79ba1d32787ebcd](https://gist.github.com/equinox2k/4e72b3fcdd9ae3e4d79ba1d32787ebcd)

**Comment by paulushub** [comment]
@equinox2k  Thanks for the information. I checked the file in the `WpfSvgTestBox` test application and cannot see any speed issue. If you click the `Convert` button a second time, it does not even blink.

Test Machine: Windows 7
CPU: Xeon E3-1226 V3 @ 3.30 GHz 
RAM: 16.0 GB
GPU: Quadro K2200 (maybe the only modern and high-end hardware)

Currently opened applications (RAM/CPU consumption):
1. Adobe Reader 
2. Opera Browser (30 tabs)
3. Chrome Browser (over 30 tabs)
4. Eclipse IDE (two different instances)
5. Visual Studio 2013, 2017 and 2019
6. Text Editor instance etc

If you can give me a little more information, I will highly appreciate it.

**Comment by equinox2k** [comment]
@paulushub ok I can confirm wpf version is ok but issue with the gdi version.

GdiTestSvgControl if you run that with the svg you should see issue, however there is a bug in demo where you have to comment out a throw...

```
        public SvgPictureBoxWindow(SvgPictureBox control, ISvgRenderer renderer)
            : base(control.Width, control.Height, renderer)
        {
            if (_svgPictureBox == null)
            {
                //throw new ArgumentNullException(nameof(control), "control cannot be null");
            }

            _preferUserSize = true;
            _svgPictureBox  = control;
        }
```

**Comment by equinox2k** [comment]
I think for some reason its spending most of its time in 

public static GraphicsPath CreatePath(SvgPathElement element) rendering approx 117000 elements

**Comment by paulushub** [comment]
@equinox2k Thanks so much for the update and the support. 

> GdiTestSvgControl if you run that with the svg you should see issue, however there is a bug in 
> demo where you have to comment out a throw...

Sorry, the GDI+ code is broken. Most likely I have committed an experimental code when fixing issues with the WPF sources. I checked and the GDI+ samples are all throwing the exceptions. Will fix this immediately.

> public static GraphicsPath CreatePath(SvgPathElement element) rendering approx 117000 elements

Sorry again, the GDI+ renderer was not receiving any update until now. I have just started improving it to bring it to the level of the WPF and also use it as the basis for .NET Core cross-platform support.

The WPF never converts the path language string to its SVG `SvgPathSeg` list, which is done once but only when requested. It directly converts the path string to its `PathGeometry`. However the GDI+ converts the path string to `SvgPathSeg` list and then converts that to `GraphicsPath`. For small path this may not be an issue, but for such large path it quickly shows. I will fix this soon.

**Comment by equinox2k** [comment]
Great really appreciated, looking forward to update

**Comment by paulushub** [comment]
@equinox2k I found that the conversion of path string to `SvgPathSeg` list is fast enough, and also needed for rendering markers later (not in this sample). 
As you rightly pointed out the problem was with the `GraphicsPath CreatePath(SvgPathElement element)` method.
There were some inefficient codes involved, but the main problem was in use of `IndexOf` when calling `PreviousSeg`. Fixing this improved the rendering speed drastically, a bit closer to the WPF renderer. 
I have committed the codes, please verify this. Thanks for the support.

**Comment by petertribe** [comment]
@paulushub

Just given it a go, works perfectly now, thanks so much for your quick response and fix :)

Is there any chance of releasing a updated nuget?

**Comment by paulushub** [comment]
Thanks, nuget with version 1.4 will be ready by Monday.

**Comment by equinox2k** [comment]
@paulushub great thanks, just incase interested I've been working on getting ImageSharp by SixLabours to be able to do parts for SVG rendering (missing the nonzero fill rule). So will be working on a extension for SharpVectors to render using ImageSharp. Additionally will be working on adaptor for cete Dynamic PDF so can embed svg into PDF's. So expect a few contributions in future.

**Comment by paulushub** [comment]
@equinox2k Thanks for the information. That is really the direction of this project now. 
With the WPF (and later SharpDX), will continue to address specific Windows programmers needs. Users trying WPF renderer in server environment had problems.

I have started abstracting the graphics of the GDI+ renderer, currently as abstract class `GdiGraphics` but will be an interface (with related interfaces for GraphicsPath, Image etc) later in the version 2 release where users can accept breaking changes!

Unfortunately, this is a long process since I still have a lot of work to do with each renderer (filters, animation, scripting etc are still pending). Just done work on the SVG fonts support for WPF and will need to port that to GDI+ after more tests.
Soon, I will start releasing separate Nuget package for each renderer, the GDI+ renderer is not matured yet.

If needed, I could add `SharpVectors.Rendering.ImageSharp` project and we can start a new rendering efforts there based on the `ImageSharp`. This could take full advantage of the `ImageSharp` features and be released as separate Nuget package, packed with its other dependent SharpVectors library.
Or, you can create a public repository on Github and I will contribute to it.

**Comment by paulushub** [comment]
@equinox2k Sorry for the Nuget package delay. I have enabled other test suites (Second Edition of the Full Specs Tests and the Tiny Specs Tests) in the W3C test applications . There are some parsing and rendering issues resulting in exceptions that need to be addressed.

BTW, I have now seen your project `SVGSharpie`.

**Comment by paulushub** [comment]
The nuget package is now available. Thanks for the support.
