### ISSUE TITLE
SharpVector app feature request: Conversion to <DrawingImage> + suggested workflow.

### ISSUE THREAD

**Issue by rerdavies** [ElinamLLC/SharpVectors#132]
First off, o thank god, bless you!!!! I am so grateful for what you have done.

Although I'm open to suggestions for workflow, currently, I paste my XAML icons into a  resource dictionary to that I can instantiate them with <Image Source={StaticResource dwgBuildIcon}" /> (for example.

The corresponding resource entry would be:

    <DrawingImage x:Key="dwgBuildIcon" >
        <DrawingImage.Drawing>
            <DrawingGroup xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
                  .... your XAML here... 
            </DrawingGroup>
        </DrawingImage.Drawing>
    </DrawingImage>

To that end, the workflow I would like to see is:

1) Drag an SVG from file explorer (e.g. an .SVG file in the VS2019 image libary), and drop it onto  the SharpVector app.

2) SharpVector converts the SVG and displays it in an edit box.

3) I copy the content of the edit box and paste it into app.xaml (actual, in my case icons.xaml, which is merged into app.xaml using MergedResourceDictionary).

In addition, it would be convenient if you included the <DrawingImage /> parent tags, or provided an option to generate the <DrawingImage> parent tags when converting.

**Comment by paulushub** [comment]
@rerdavies I understand this issue and had a plan to resolve it. The current SharpVectors converter application seriously needs an update and I am looking into redesigning it.
For suggestions, there is an application that currently provides that support (I have not tested or used it) by @BerndK: [SvgToXaml](https://github.com/BerndK/SvgToXaml)

It is not updated for months, so if you need the latest version of the SharpVectors, it used the package so you can update and recompile it.

**Comment by BerndK** [comment]
@rerdavies Ok, I see your point. The idea was to make it even more simple and automated. I would place all svg into a dir and let SvgToXaml automatically create all the file. You migth have noticed that SvgToXaml is a hybrid app - it can also be used from commandline, see samples.
So your workflow will simplify by placing many svgs to a dir and run the batch. That workflow will also support changes on the SVG that then might reflect in the related generated file.
Otherwise you are free to modify the app.
@paulushub please note that if I remember correctly, I made some minor changes in the original SharpVectors code. So not sure if everything works after a simple update.

**Comment by paulushub** [comment]
> please note that if I remember correctly, I made some minor changes in the original 
> SharpVectors code. So not sure if everything works after a simple update.

@BerndK If you remember, let me know the types of changes you made. I have plans to add support for `ResourceDictionaryConverter` that will handle the creation of resource dictionary for the WPF and simplify such uses.

**Comment by BerndK** [comment]
@paulushub I can't remember exactly what the reason was to 'fork' that component. I think I did investigate this a year ago and didn't find the exact reasons. On the other way I'm sure there was something I wanted to change.
Sorry that I can't provide clear facts. I would suggest to just go on. If all Tests still are green, it should be OK. If the tests will fail, we should dig deeper.

**Comment by paulushub** [comment]
@rerdavies @BerndK I have made changes to support the ResourceDictionary. Sorry for the delay, can you help with some feedbacks?
