### ISSUE TITLE
Support for .NET 5.0 single file applications

### ISSUE THREAD

**Issue by Droppers** [ElinamLLC/SharpVectors#205]
I tried to publish my application, but unfortunately `Assembly.GetExecutingAssembly().Location` will return an empty string for .NET 5.0 single file applications.

As per the documentation: "In .NET 5.0 and later versions, for bundled assemblies, the value returned is an empty string."

I think the solution is to use `Process.GetCurrentProcess().MainModule.FileName` or `AppContext.BaseDirectory`, but the latter is only supported on .NET Core projects.

https://github.com/ElinamLLC/SharpVectors/blob/ff1bfec5774f7db6e1673c03deed2d003f22b546/Source/SharpVectorRenderingWpf/Utils/WpfSvgWindow.cs#L136

https://github.com/ElinamLLC/SharpVectors/blob/ff1bfec5774f7db6e1673c03deed2d003f22b546/Source/SharpVectorRenderingWpf/Utils/WpfSvgWindow.cs#L184

**Comment by Droppers** [comment]
I should note that I can work around it by supplying a `Uri` to `FileSvgReader.Read(Uri)` instead of fileName string, but it is still not expected behavior.

**Comment by paulushub** [comment]
@MihailsKuzmins Recently submitted changes to use the `AppContext.BaseDirectory`, it seems there is still more to do! 
Related to Issue #199

**Comment by MihailsKuzmins** [comment]
sorry, I fixed it only the places where I had had the same issued, so I haven't searched for all occurrences of this problem (I think I should have done it though). I should try better next time. Sorry.

The extension is located in the core project and should be accessible from any place in the codebase (presumable some overloads might be needed)
https://github.com/ElinamLLC/SharpVectors/blob/489d1248fa6e76f0eff228c6db7a55f0cba973d9/Source/SharpVectorCore/Utils/PathUtils.cs#L10

**Comment by paulushub** [comment]
@MihailsKuzmins  No need for an apology. I only wanted you to handle it, so I referenced you. Hope you will fix, you are a contributor to this repository.

**Comment by MihailsKuzmins** [comment]
@paulushub-san. Thank you for the trust. I will do my best to fix this today or tomorrow 😄

**Comment by paulushub** [comment]
@MihailsKuzmins Thanks for the understanding! 
No pressure, I will be happy if you can get it by Monday, then I will try posting a Nuget package by Tuesday with other fixes.

**Comment by paulushub** [comment]
@MihailsKuzmins 
> It is almost 1 a.m., so I am going to take a break 

Sorry, please do get enough rest. 
I work at home through the night due to the heat, working on a new project (SharpIcons) to provide vector icons for WPF and related projects. Many are using SharpVectors for icons, and will be better served by the SharpIcons.
Currently without a contract due to the pandemic (main source of contracts is frozen all new contracts). 😞 

> WPF for sure, something else?

For now, we are targeting WPF and WinForms. Hoping to target MAUI, but it might not be this code base.

**Comment by MihailsKuzmins** [comment]
@paulushub-san,
Oh, SharpIcons, I am looking forward to seeing this project in action. It is not published in NuGet, so I assume the work is still in progress. If you need some assistance I might try to help you (my experience with rendering images is as good as nothing, but anyways 😄).
Yeah, damn virus. Luckily for me I was able to retain my position at a Latvian company, but moving around is quite problematic due to the emergency state

> For now, we are targeting WPF and WinForms.
OK, this seems like not much to test. I will try to fix the issue @Droppers has and play around with the `AppDomain` staff

**Comment by paulushub** [comment]
> Oh, SharpIcons, I am looking forward to seeing this project in action.

Currently, in private mode. Icon models include (similar to the icon sources in UWP/Windows.UI.Xaml.Controls)
* Path Icons
* Font Icons 
   * Symbol Icons
   * Material Icons
   * Fluent Icons
   * Font Awesome
   * Bootstrap
 * Emoji Icons (Monochrome and Colored)
 * Svg Icons
 
The colored icons for emoji fonts are available as SVG tag, which means having to parse the font files as the SVG font tag/table are not supported by WPF and Win32 font API. Only available on latest DirectWrite for Windows 10+.
If I get over this feature, I will make it public with beta Nuget package for reviews.

> but moving around is quite problematic due to the emergency state

Yeah, already moving around Tokyo is not easy. Had some job opportunities there before but cannot accept living in Tokyo - I love quiet environments. Well, more strength to you 🔋

**Comment by MihailsKuzmins** [comment]
Oh, yes, Tokyo is a 賑やかな町 (emm, I guess it's "crowded" in English), but I chose Tokyo as a start of my journey because there are a lot of opportunities in the city (well, much less due to the emergency state). One day I want to move to Hokkaido or to the Okayama area (I have always liked the bay area around Shikoku)
One day probably...

**Comment by paulushub** [comment]
@Droppers The updated fix is now available in the repository. Please verify this and give us feedback.

**Comment by MihailsKuzmins** [comment]
@paulushub-san. Since we are not getting any feedback may we consider that the issue is resolved?

**Comment by paulushub** [comment]
@MihailsKuzmins Yes, the issue considered resolved. It will be closed after a Nuget release.
