### ISSUE TITLE
SharpVectors for macOS and linux

### ISSUE THREAD

**Issue by yuriyhanysh** [ElinamLLC/SharpVectors#227]
Hey!
Thank you for creating this beautiful library 🙏 

Is it possible to use this project on macOS and Linux platforms?

**Comment by paulushub** [comment]
> Thank you for creating this beautiful library

Thanks for the complement.

> Is it possible to use this project on macOS and Linux platforms?

Sorry, currently no. The WPF is Windows only and the GDI+ support through `System.Drawing.Common` is dropped by Microsoft.

However, we have plans to support other rendering platforms, with the newly released Maui Graphics as the next candidate. With this support, we will have the cross-platform (MacOS and Linux) and ASP.NET.

**Comment by yuriyhanysh** [comment]
@paulushub, what about core functionality and not rendering itself?
Would it be possible to create .NET6.0 CLI to convert SVG into XAML that works on macOS and Linux? 
Probably when only using this project's `Core`, `Dom`, and `Module` parts? Or are they also Windows only?

**Comment by paulushub** [comment]
> what about core functionality and not rendering itself?
> Probably when only using this project's Core, Dom, and Model parts? Or are they also Windows only?

The Core, Dom and Model parts are .NET Standard 2.1, so you can use it on any system supporting that.

> Would it be possible to create .NET6.0 CLI to convert SVG into XAML that works on macOS and Linux?

You can if you implement a generic version of the WPF drawing classes. SharpVectors does not simply convert SVG to XAML, the SVG is rendered into WPF DrawingGroup object, and the rendered object is saved to XAML if needed. That rendering part requires the WPF assemblies.

What possible uses do you wish for this kind of support since XAML is mainly Windows? (I might help, if there is enough user base for your use case!)

**Comment by yuriyhanysh** [comment]
> What possible uses do you wish for this kind of support since XAML is mainly Windows? (I might help if there is enough user base for your use case!)

My use case is automating asset generation for different platforms (win, mac, mobile) from one source (SVG).

I thought it could be done by simply wrapping existing functionality in the CLI interface to use it on Linux. But as it is not the case, and not many people need to have XAML on Linux, it may not be worth doing. 🤷 

Thank you for clarifying my questions! 🙏
