### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by ravenpride** [ElinamLLC/SharpVectors#65]
Hello development team,

is deployment via nuget.org planned in the near future? If not, I'd be happy to contribute it.

Regards

**Comment by paulushub** [comment]
@ravenpride Thanks for the interest. The initial target was to create converters, and also have reusable libraries for developers.
The nuget packages are now planned but I am currently trying to restructure the codes. I did this earlier, but the project moved to Github and under Git so have to rework it all again, otherwise I will loose the history and others.

If interested, you can submit a pull request. Thank you.

**Comment by ravenpride** [comment]
Hello jenokizm,

the code for building the Nuget Package is already merged (see PR #66). Paul said, he'll integrate AppVeyor soon, so releases can be automatically built and published to Nuget.org. We'll get packages soon :-)

**Comment by paulushub** [comment]
SharpVectors.Reloaded now available as Nuget package, sorry for the delay.

https://www.nuget.org/packages/SharpVectors.Reloaded/1.1.0

The package was manually built for now, will start using AppVeyor later. I think there is still more work needed on the projects configuration. Hopefully soon, I will move it under AppVeyor.
Thanks for the support.
