### ISSUE TITLE
Not see the picture at runtime

### ISSUE THREAD

**Issue by jenokizm** [ElinamLLC/SharpVectors#67]
Hey. I compiled a fresh version of your library, connected it to my project and use it like this:
`<svgc:SvgViewbox Margin="5,5,0,0" Height="317" Width="330" Stretch="Uniform" Source="Newpegi_3.svg" HorizontalAlignment="Left" VerticalAlignment="Top"/>`

At the same time I see a picture in the visual designer, but when I run the program the picture does not appear (

ps image from this https://upload.wikimedia.org/wikipedia/commons/e/e1/Newpegi_3.svg but I do not specify the link but put it locally in the project

**Comment by paulushub** [comment]
@jenokizm Please take a look at the tutorial sample **SvgImageSample** in the following directory to see the various ways to link the svg file in your application; web, local and resources.

> SharpVectors\Samples\SharpVectorsControlSamples\SvgImageSample

**Comment by jenokizm** [comment]
Thanks for the answer. But you closed the topic early. I installed a fresh package from Nuget and connected it as in the example picture, but it is not shown.
I am sending you a draft, please point out the mistake and correct my project.
[WpfApp1.zip](https://github.com/ElinamLLC/SharpVectors/files/2346361/WpfApp1.zip)

**Comment by paulushub** [comment]
@jenokizm The original problem was due to the unsupported **https** protocol, because at the time there was no samples to test.
I enabled the https protocol and it worked so I closed the issue.

You have not really looked at the **SvgImageSample**, you need to set the **Build Action** of the **Newpegi_3.svg** file to **Resource** for your sample to display the image, it is currently set to **Content**.

**Comment by jenokizm** [comment]
Yes, I really missed it! Now everything worked. Thank you.
