### ISSUE TITLE
files without document size defined as 640x480

### ISSUE THREAD

**Issue by jhndnnqsc** [ElinamLLC/SharpVectors#78]
If I import an SVG without a document size defined in the SVG it imports with the default document size of 640x480. Is there a way to disable this behavior and use the extents of the items instead? In version 1.0.0.0 it would import using the extents of the graphic elements. Documents with the size correctly specified import correctly without any issues. I've attached an example.
[nosize.zip](https://github.com/ElinamLLC/SharpVectors/files/2535058/nosize.zip)

**Comment by paulushub** [comment]
Sorry John, there was a work around a problem of saving the exact size of images. It is currently marked as TODO in the
`SharpVectors.Rendering.Wpf/Wpf/WpfSvgRendering.cs` file (line 176-185).
I will implement a better way out and update the sources soon. Again, sorry for the inconvenience.

**Comment by paulushub** [comment]
Hello John, I have removed the default size completely. For the WPF/XAML rendering, the default size is not  really required.
Before, it defined the clip region for the output and for saving the original size of the image, a transparent box was drawing using this region so that the XAML drawing can have a definite size.

The size is now moved to Settings (with defaults as width=-1, height=-1, i.e not set).

I have committed this fix, please verify this issue for me and I will prepare a new release 1.2 this week.

**Comment by jhndnnqsc** [comment]
Hi Paul-

Thanks for looking at this. That change does fix the issue with documents without a size defined. I did notice that it also changes the behavior when a document size is defined that doesn't match the extents of the graphic elements. In the previous version it would use the document size if it was defined. To be honest I'm not 100% sure what the correct approach is here - probably the most useful thing might be an option in WpfDrawingSettings that allowed either behavior.

**Comment by jhndnnqsc** [comment]
The `EnsureViewBoxSize` property works as I would expect. Thanks again, John
