### ISSUE TITLE
Problem with SVG logo

### ISSUE THREAD

**Issue by thrunge** [ElinamLLC/SharpVectors#96]
Hello!

I tried to display this SVG logo with SharpVector: https://www.w3.org/Icons/SVG/svg-logo-v.svg 

But I found two issues:
1) the white letters ("#SVG" element) are not visible. It seems that there is a problem with the defs tag that leads the letters to be displayed under the "#base" element. If I remove the opening and closing defs tag in lines 29 and 35 (leaving the content untouched) or move the following groups into the defs element the letters are shown correctly.
2) the opacity of the black box ("#base" element) is ignored.

Are these issues a problem with the svg file or a problem with my usage of SharpVector or a bug?

**Comment by paulushub** [comment]
Issue verified, failing to display even SVG logo sucks badly!!!
I will fix it immediately!
@thrunge Thanks for reporting it.

**Comment by paulushub** [comment]
Found the source of the problem. The current implementation of the `use element` is the problem.
The current implementation temporally removes the `referenced element` from its parent element, attaches it to the use element and renders it like a group element.
After rendering it detaches the `referenced element` and appends it to the original parent element. This works without a problem if the `referenced element` is a child of a `defs element`. Otherwise, it position is changed and in this case is rendered twice, covering the `use elements` rendered before it.

The solution is the clone the `referenced element` and attach it to the `use element` and detach it after rendering.

I will commit the changes soon.

**Comment by paulushub** [comment]
Finally committed the fixes to resolve this issue: ad7b893660c31eba18dba84e36145dab4d216e97
Please verify.

**Comment by thrunge** [comment]
The printing order and opacity problems are fixed, but the percentage value is still ignored.

Would you prefer a new issue for that?

**Comment by paulushub** [comment]
By the SVG specs, for the svg tag, the width and height defines the intrinsic size. Since we are converting from a vector to another vector graphics (XAML), defining intrinsic size will only mean scaling the final output (applying a transform). 

WPF in most cases (like viewbox, image source) defines properties to size and scale the drawings so there was no need to support the intrinsic size. Will be relevant in GDI+ (or Windows Forms) rendering for instance.
If, however, you have a need for this then please consider posting new issue since it must be handled in a way not to break existing applications.

**Comment by thrunge** [comment]
You are right, usually there will be an element around the image that defines the size anyway, so I see your point that this is not necessary.

Thanks again for the fast reaction and fix!
